[package]
name = "slint-qt"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
slint = { version = "1.9", features = ["raw-window-handle-06", "renderer-winit-skia", "backend-winit"] }
raw-window-handle = "0.6"
crossbeam-channel = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.14"
sysinfo = "0.38.4"

dirs = "5.0"
sys-locale = "0.3"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Graphics_Dwm", "Win32_UI_Controls", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging", "Win32_UI_Shell", "Win32_System_Com", "Win32_System_Threading", "Win32_System_Registry", "Win32_Graphics_Gdi", "Win32_System_DataExchange", "Win32_System_Memory"] }

[build-dependencies]
slint-build = "1.9"
cbindgen = "0.29.2"
